language: node_js
matrix:
  include:
    - os: linux
      node_js: stable
    - os: linux
      node_js: 8.9
    - os: windows
      node_js: latest
    - os: windows
      node_js: 8.9

before_install:
  - npm install -g npm@6
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm run build

install:
  # travis does npm ci by default
  - npm install

script:
  - npm test
    # Don't fail the build bc of this yet.
  - npm run test:check-coverage || true
  - npm run prod

after_script:
  - greenkeeper-lockfile-upload
